import {
  CLIENT_TAB_PLUGIN_VERSION,
  CLIENT_TAB_PROTOCOL_VERSION,
  type CompanionSnapshot,
} from "@summonerkit/contracts";

export const emptySnapshot: CompanionSnapshot = {
  revision: 0,
  connection: {
    status: "discovering",
    phase: "Waiting for League",
    region: null,
    locale: null,
    patch: null,
    capabilities: {
      championCatalog: false,
      skinInventory: false,
      lootInventory: false,
      readyCheck: false,
      champSelect: false,
      runes: false,
      summonerSpells: false,
      presence: false,
      clientTab: false,
    },
    connectedAt: null,
    lastError: null,
  },
  presence: {
    status: "unavailable",
    availability: null,
    updatedAt: null,
    lastError: "Connect to League to manage presence.",
  },
  collection: {
    status: "idle",
    source: "none",
    stale: false,
    patch: null,
    accountKey: null,
    updatedAt: null,
    progress: {
      totalSkins: 0,
      ownedSkins: 0,
      lootSkins: 0,
      favoriteSkins: 0,
      wishlistSkins: 0,
      completionPercent: 0,
    },
    champions: [],
    warnings: [],
  },
  automation: {
    riskAcknowledged: false,
    executionMode: "dry-run",
    autoAccept: false,
    autoPick: false,
    autoBan: false,
    autoSpells: false,
    autoRunes: false,
  },
  startup: {
    launchOnWindowsStartup: false,
    openOnLeagueDetected: false,
  },
  pendingAutomation: [],
  profiles: [],
  audit: [],
  integrations: [
    {
      id: "rose",
      name: "Rose",
      installed: false,
      running: false,
      managedProcess: false,
      executablePath: null,
      version: null,
      lastError: null,
    },
    {
      id: "deceive",
      name: "Deceive",
      installed: false,
      running: false,
      managedProcess: false,
      executablePath: null,
      version: null,
      lastError: null,
    },
    {
      id: "pengu",
      name: "SummonerKit client tab",
      installed: false,
      running: false,
      managedProcess: false,
      executablePath: null,
      version: null,
      lastError: null,
    },
  ],
  clientTab: {
    installed: false,
    expectedPluginVersion: CLIENT_TAB_PLUGIN_VERSION,
    installedPluginVersion: null,
    installedProtocolVersion: null,
    activePluginVersion: null,
    protocolVersion: CLIENT_TAB_PROTOCOL_VERSION,
    activeProtocolVersion: null,
    restartRequired: false,
    lastRepairAt: null,
    lastError: null,
  },
  doctor: {
    overall: "unavailable",
    checkedAt: new Date(0).toISOString(),
    checks: [],
  },
  aram: {
    active: false,
    currentChampionId: null,
    bench: [],
    favoriteChampionIds: [],
    availableFavoriteChampionIds: [],
    rerollsRemaining: null,
    rerollPoints: null,
    updatedAt: null,
  },
  session: {
    queue: {
      activity: "unavailable",
      lobbyAvailable: false,
      queueId: null,
      searchState: null,
      canStart: false,
      canStop: false,
    },
    readyCheck: {
      active: false,
      state: null,
      canAccept: false,
      canDecline: false,
    },
    championSelect: {
      active: false,
      sessionId: null,
      timerPhase: null,
      timerRemainingMs: null,
      timerUpdatedAt: null,
      localPlayerCellId: null,
      localAction: null,
      myTeam: [],
      theirTeam: [],
      myTeamBans: [],
      theirTeamBans: [],
      pickableChampionIds: [],
      bannableChampionIds: [],
      selectedChampionId: null,
      selectedSkinId: null,
      spell1Id: null,
      spell2Id: null,
    },
    summonerSpells: [],
    runePages: [],
  },
  insights: {
    guidance: {
      status: "idle",
      source: "none",
      endpoint: null,
      schemaVersion: null,
      providerName: null,
      checkedAt: null,
      generatedAt: null,
      currentPatch: null,
      currentPatchCovered: null,
      observationCount: null,
      cohortSize: null,
      lookbackDays: null,
      coverage: { recommendations: 0, builds: 0, draftSignals: 0, patchImpacts: 0, champions: 0, patches: [] },
      lastError: null,
    },
    runes: {
      status: "idle",
      source: "none",
      stale: false,
      providerName: null,
      updatedAt: null,
      recommendations: [],
      perks: [],
      warnings: [],
    },
    coach: {
      status: "idle",
      source: "none",
      stale: false,
      providerName: null,
      updatedAt: null,
      builds: [],
      draftSignals: [],
      patchImpacts: [],
      items: [],
      warnings: [],
    },
    performance: {
      status: "idle",
      source: "none",
      stale: false,
      matchesAnalyzed: 0,
      windowLabel: "Recent 100 matches available in this client",
      updatedAt: null,
      summary: { games: 0, championsPlayed: 0, winRate: 0, kda: 0, farmPerMinute: 0, overallScore: 0 },
      champions: [],
      matches: [],
      warnings: [],
    },
  },
  remote: {
    status: "unavailable",
    relayConfigured: false,
    relayUrl: null,
    mobileUrl: null,
    activeDeviceId: null,
    lastError: null,
  },
  remoteDevices: [],
};
